### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by samford** [simon-budig/woof#15]
Hi, we're working on updating the woof formula in Homebrew (Homebrew/homebrew-core#94258) to a version that supports Python 3, in anticipation of the system Python 2 being removed in macOS 12.3. However, the woof repository doesn't have any version tags or releases and one of our Project Leadership Committee (PLC) members has made it clear that we should only update the formula to a new upstream release.

That is to say, it's not appropriate for us to simply pick the newest commit and use the commit date as the version, as it's not an official release. Not having any version information to reference also makes it difficult for us to check for new versions, as we would have to manually check the commit history instead of programmatically checking the repository tags/releases for new versions.

The homepage previously published date-based versions (e.g., `woof-2012-05-31.py`, `woof-2009-12-27.py`, etc.) but a new version hasn't been officially released since 2012-05-31. Unfortunately, that release came from the commit before Python 3 support was added, so the woof formula is facing removal if it can't be updated to a newer version.

With this in mind, could you please create version tags (e.g., `2021-06-09`) for releases? If it makes sense for you, it would be helpful to create a version tag for an up-to-date version, so there's something we can use in the related Homebrew PR.

**Comment by simon-budig** [comment]
I've now added a tag "woof-20220202" (could not resist the date...). Can you please verify if this is usable for you in that form?

Thanks for bringing this problem to my attention.

**Comment by samford** [comment]
Yes, that's what we needed and I imagine it will benefit other [package managers](https://repology.org/project/woof/versions) as well. Going forward, the Homebrew formula will only be updated to a new version when you release it (like here).

I've updated the related Homebrew version bump PR (https://github.com/Homebrew/homebrew-core/pull/94258) to use the new tag archive and it shouldn't have any trouble being merged when it's ready.

Thanks for your help!
