### ISSUE TITLE
Clarification: -Z zipped tarball OR actual zip file?

### ISSUE THREAD

**Issue by fancsali** [simon-budig/woof#2]
I think I've spotted something in the help/documentation on Debian; the manpage says:

```
       -Z <dir>
              Used on a directory, it creates a tarball with ZIP compression
```

However, I am fairly confident, that would actually create a proper zip archive file. Otherwise this is a kind of a trap for people if they share files with non-*nix users.

**Comment by CoolCat467** [comment]
> When a directory is specified, an tar archive gets served. By default
> it is gzip compressed. You can specify -z for gzip compression,
> -j for bzip2 compression, -Z for ZIP compression or -u for no compression.

**Comment by simon-budig** [comment]
Yeah, that is a mis-wording. Thanks for spotting.

Will look into this.

**Comment by simon-budig** [comment]
This is apparently a problem with the debian packaging, the word "tarball" does not appear in this repository, maybe they generated the man page from some older version.

Please report this against the debian package.

Thanks!
