### ISSUE TITLE
When using woof to send directories, client saves filename without compression extention

### ISSUE THREAD

**Issue by CoolCat467** [simon-budig/woof#4]
When you use woof to send (in my testing) any directory, the default filename sent to clients to use is missing the compression file extension.

For example, trying to sent the directory "Documents" to someone with gzip compression, the filename should be "Documents.tar.gz", but when you download the file, firefox and woof's own tiny web browser (and probably everything else) wants to save the file as only "Documents", no "tar.gz" extension.

**Comment by simon-budig** [comment]
Dieses Problem ist behoben, ich habe es in Commit #39a7b82f gefixt.

Danke!
